language: 'elixir'

matrix:
  include:
  - elixir: 1.6
    otp_release: 19.3
  - elixir: 1.6
    otp_release: 20.3
  - elixir: 1.6
    otp_release: 21.3
  - elixir: 1.7
    otp_release: 19.3
  - elixir: 1.7
    otp_release: 20.3
  - elixir: 1.7
    otp_release: 21.3
  - elixir: 1.8
    otp_release: 20.3
  - elixir: 1.8
    otp_release: 21.3

script: ./priv/scripts/ci-check.sh
